### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by bhagwatposane** [kenfar/DataGristle#61]
While I run below command
 `$ gristle_determinator sample.csv `

I get error:
Invalid syntax on line 398 
self.division: str = None

Also I get similar errors while running other modules ex. gristle_validator.

**Comment by kenfar** [comment]
I think you're using an older python - it now requires python 3.6 to support fstrings and in this case type annotations.

**Comment by bhagwatposane** [comment]
Hi Kenfar,
FYI, I am using python 3.6

**Comment by kenfar** [comment]
Can you double-check?    Because that particular error message shows up with python3.5 - not 2.7 or 3.6.
You can see by running:  $ python -V
Let me know if you need help upgrading to python3.6 or getting an older version of datagristle for python3.5

**Comment by bhagwatposane** [comment]
I checked it, The python version is  3.6.0, Please see the attached for error and version details.

![image_92](https://user-images.githubusercontent.com/29473793/33753603-19955c4e-dc0e-11e7-91c3-b32fe583be2d.png)

**Comment by kenfar** [comment]
Wow, that's really odd.  Can you do one more check for me?  Let me know what the shebang line (first line) in the instance of gristle_determinator that you're running says:

- $ which gristle_determinator     
- head -n 1 <the exact path reported by the which command>

It should look something like:

#!/home/kenfar/Envs/dg36/bin/python3.6

But I suspect it's pointing at python3.5

**Comment by bhagwatposane** [comment]
Thanks Kenfar for the inputs !
I have some discrepancies for pointing to right python version.
