### ISSUE TITLE
How to measure data quality?

### ISSUE THREAD

**Issue by bhagwatposane** [kenfar/DataGristle#63]
```
        Name:             sa
        Field Number:     2
        Wrong Field Cnt:  0
        Type:             integer
        Min:              -999
        Max:              52
        Unique Values:    35
        Known Values:     35
        Mean:             2.45454545455
        Median:           38.0
        Variance:         31470.2681359
        Std Dev:          177.398613681
        Top Values:
            41                                       x 7 occurrences
            42                                       x 7 occurrences
            39                                       x 6 occurrences
            37                                       x 5 occurrences
            46                                       x 5 occurrences
            17                                       x 4 occurrences         
```

I want to find min and max threshold for the bulk data present. 
for ex. if data range is (-992, 52) in above example but the bulk data is present in between (1, 14) and remaining data points are outliers.

Can we measure such threshold using datagristle ?

**Comment by kenfar** [comment]
Yes - the gristle_validator applies a json schema against the csv files.   Within that schema you can include minimum & maximum values for any int/float field.  A few usage nots:

- minimum & maximum require int/floats, but the csv modules just returns all strings (unlike the json module that'll return ints & floats when appropriate).  So, for that reason gristle_validator also recognizes dg_type, dg_minimum & dg_maximum - in which you can provide a dg_type of int, and the program was cast those to ints for dg_minimum & dg_maximum.
- you can see an example yaml schema for gristle_validator in the readme for the project
- the data directory within this project has a number of schema files that you can use as examples
- the test file: test_gristle_validator_cmd.py generates schemas and data and runs them through the validator.

Good luck
