### ISSUE TITLE
pip=> 10. datagristle install issue

### ISSUE THREAD

**Issue by deering59** [kenfar/DataGristle#65]
Trying to install DataGristle while having pip version 10 and higher, following error occurs:

`pip3 install datagristle`
`Collecting datagristle`
  `Downloading` 
`<..>`
  `  Complete output from command python setup.py egg_info:`
    `Traceback (most recent call last):`
   `   File "<string>", line 1, in <module>`
  `    File "/tmp/pip-install-0yef2cxh/datagristle/setup.py", line 6, in <module>`
 `       from pip.req import parse_requirements`
`    ModuleNotFoundError: No module named 'pip.req'`

**Comment by kenfar** [comment]
Issue is resolved:  setup.py changed to support pip10, and cletus dependency also upgraded to version that supports pip 10.

Thanks for the notification.
