### ISSUE TITLE
gristle_validator - no column name in error output

### ISSUE THREAD

**Issue by kgeographer** [kenfar/DataGristle#69]
Using a slightly altered version of the example schema and a small data file, I get '**\<obj\>[2]**' for a field name. This does not happen for errors in column 0, only columns that follow. Delimiter doesn't seem to matter, tried tabs, semicolons and commas.

I've poked at the code and find no string "is not in the enumeration" so I can't locate where to try and address this. Same result when I create a comparable json version of the schema.

I get this output from the following command and files:
`3       2019-09-09      Genova  Value 'Genova' for field '' Failed to validate field 'data' list schema: Value 'Genova' for field '<obj>[2]' is not in the enumeration: ['Milan', 'Siena', 'Pavia']`

`gristle_validator sample.csv --hasheader --validschema sample_schema.yml -e errors.txt`

**sample_schema.yml**
```
items:
  - title:            rowid
    blank:            False
    required:         True
    dg_type:          integer
    dg_minimum:       1
    dg_maximum:       60
  - title:            start_date
    blank:            False
    minLength:        8
    maxLength:        10
    pattern:          '[1-2][0-9][0-9][0-9]-[0-9]*-[0-9]*'
  - title:            location
    blank:            False
    minLength:        2
    maxLength:        100
    enum:             ['Milan','Siena','Pavia']
```
**sample.csv**
```
rowid	start_date	location
1	2019-09-07	Milan
2	2019-09-08	Siena
3	2019-09-09	Genova
4	2019-09-10	Pavia
```
The package looks like it will be very useful for me, but I'd prefer not to parse the \<obj\>[2] in presenting results to users. Thanks

**Comment by kenfar** [comment]
Makes perfect sense.  I think the issue is a limit of the underlying schema validation module (Validictory).  I'll take a closer look to confirm and look at replacing this deprecated module.

**Comment by kenfar** [comment]
Done - with the switch from validictory to jasonschema
